#!/usr/bin/env bash

if [ -n "$VERSION" ] ; then
    VERSION="-k$VERSION"
fi

docker run \
    --rm -t -i \
    -v $SSH_AUTH_SOCK:/auth.sock \
    -e SSH_AUTH_SOCK=/auth.sock \
    -e VERSION=$VERSION \
    -v $(pwd):/opt/kernels \
    -v ~/.gitconfig:/root/.gitconfig \
    kernels $1

