#!/usr/bin/env bash

TMPDIR="$(mktemp -d)"
KERNELDIR="$(pwd)"

git clone git://git.code.sf.net/p/aufs/aufs3-standalone "$TMPDIR"
pushd "$TMPDIR"
git checkout aufs3.x-rcN
popd

for patch in aufs3-kbuild.patch aufs3-base.patch aufs3-mmap.patch ; do
    patch -p1 < "$TMPDIR/$patch"
done

pushd "$TMPDIR"
cp -v --parent -R Documentation fs include/uapi/linux/aufs_type.h $KERNELDIR/

